document.writeln("<link type=\'text/css\' rel=\'styleSheet\' href=\'css/myCSS.css\' />");
document.writeln("<link type=\'text/css\' rel=\'styleSheet\' href=\'css/bootstrap.min.css\' />");

document.writeln("<!-- -------------------------导航栏------------------------- -->");
document.writeln("");
document.writeln("		<nav class=\'navbar navbar-default\' role=\'navigation\'>");
document.writeln("			<div class=\'container-fluid\'>");
document.writeln("				<div class=\'navbar-header\'>");
document.writeln("					<a href=\'/0826\'><img class=\'img-rounded\' src=\'imgs/logo_2.png\' width=\'190px\'");
document.writeln("						height=\'50px\'></a>");
document.writeln("				</div>");
document.writeln("				<div>");
document.writeln("					<ul class=\'nav nav-pills\' style=\'margin: 0 0 0 20px;\'>");
document.writeln("						<li class=\'leader\'><a href=\'/0826\'>首页儿</a></li>");
document.writeln("						<li class=\'leader\'><a href=\'/0826/zj\'>足迹鸭</a></li>");
document.writeln("						<li class=\'leader\'><a href=\'/0826/sg\'>时光影集</a></li>");
document.writeln("						<!-- ------------------下拉导航------------- -->");
document.writeln("						<li class=\'dropdown\' style=\'margin-top: 5px\'><a class=\'dropdown-toggle\'");
document.writeln("							data-toggle=\'dropdown\' title=\'记得把声音调小哦\'>小窝窝<b class=\'caret\'></b>");
document.writeln("						</a>");
document.writeln("							<ul class=\'dropdown-menu\'>");
document.writeln("								<li><a href=\'/0826/zxt\'>找相同哦</a></li>");
document.writeln("								<li><a href=\'/0826/llk\'>连连看看</a></li>");
document.writeln("								<li><a href=\'/0826/zz\'>蜘蛛纸牌</a></li>");
document.writeln("								<li><a href=\'/0826/ppl\'>泡泡龙 </a></li>");
document.writeln("								<li><a href=\'/0826/sj\'>来打鸭子</a></li>");
document.writeln("								<li><a href=\'/0826/mota\'>魔塔beta</a></li>");
document.writeln("								<li class=\'divider\'></li>");
document.writeln("								<li><a href=\'/0826/zhh\'>种花花</a></li>");
document.writeln("							</ul></li>");
document.writeln("						<!-- ------------------------------------- -->");
document.writeln("");
document.writeln("                      <li class=\'leader\'><a href=\'/0826/happy\'>内涵段子</a></li>");
document.writeln("						<li class=\'leader\'><a href=\'/0826/sh\'>我要嗦发</a></li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</nav>");
document.writeln("		<!-- ------------------------------------- -->");